/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery-map` | `/active-delivery-map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/delivery-status-controls` | `/delivery-status-controls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/nearby-orders` | `/nearby-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/order-preview` | `/order-preview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/qr-code` | `/qr-code`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/active-delivery-map` | `/active-delivery-map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/delivery-status-controls` | `/delivery-status-controls`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/layout` | `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/nearby-orders` | `/nearby-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/order-preview` | `/order-preview`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/qr-code` | `/qr-code`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/layout${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/active-delivery-map${`?${string}` | `#${string}` | ''}` | `/active-delivery-map${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/availability-toggle${`?${string}` | `#${string}` | ''}` | `/availability-toggle${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/delivery-status-controls${`?${string}` | `#${string}` | ''}` | `/delivery-status-controls${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/layout${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/nearby-orders${`?${string}` | `#${string}` | ''}` | `/nearby-orders${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/order-preview${`?${string}` | `#${string}` | ''}` | `/order-preview${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/qr-code${`?${string}` | `#${string}` | ''}` | `/qr-code${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery-map` | `/active-delivery-map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/delivery-status-controls` | `/delivery-status-controls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/nearby-orders` | `/nearby-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/order-preview` | `/order-preview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/qr-code` | `/qr-code`; params?: Router.UnknownInputParams; };
    }
  }
}
