/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/pod-scan` | `/pod-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/report-failure` | `/report-failure`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/pod-scan` | `/pod-scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(delivery)'}/report-failure` | `/report-failure`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/active-delivery${`?${string}` | `#${string}` | ''}` | `/active-delivery${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/availability-toggle${`?${string}` | `#${string}` | ''}` | `/availability-toggle${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/pod-scan${`?${string}` | `#${string}` | ''}` | `/pod-scan${`?${string}` | `#${string}` | ''}` | `${'/(delivery)'}/report-failure${`?${string}` | `#${string}` | ''}` | `/report-failure${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/active-delivery` | `/active-delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/availability-toggle` | `/availability-toggle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/pod-scan` | `/pod-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(delivery)'}/report-failure` | `/report-failure`; params?: Router.UnknownInputParams; };
    }
  }
}
